sudo: required

services:
  - docker

language: node_js
node_js:
 - "lts/*"

cache:
  directories:
    - node_modules

script:
  - npm run test 

after_success:
  - docker --version
  - pip install --user awscli 
  - export PATH=$PATH:$HOME/.local/bin 
  - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
  - docker build -t prapor .
  - docker tag prapor:latest "${AWS_ACCOUNT_ID}".dkr.ecr.eu-west-1.amazonaws.com/prapor:latest
  - docker push "${AWS_ACCOUNT_ID}".dkr.ecr.eu-west-1.amazonaws.com/prapor:latest
  - aws ecs update-service --cluster Discord-Bots --service Prapor --region eu-west-1 --force-new-deployment